/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickorder2.Consulta;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import static quickorder2.Registro.Herramientas.Imagenes.cargarYescalar;

/**
 *
 * @author Mauro
 */
public class DetalleRestaurante extends javax.swing.JDialog {

    /**
     * Creates new form DetalleRestaurante
     */
    private ArrayList imgs;
    private int imagenSeleccionada = 0;

    public DetalleRestaurante(java.awt.Frame parent, String nick) {
        super(parent, true);
        initComponents();
        cargarDatos(nick);
    }

    private void cargarDatos(String nick) {
        webservices.DataRestaurante restaurante = quickorder2.QuickOrder2.port.buscarRestaurante(nick);
        Iterator ITimg = quickorder2.QuickOrder2.port.restauranteGetImagenes(nick).iterator();
        if (!ITimg.hasNext()) {
            BtnAtras.setEnabled(false);
            BtnAdelante.setEnabled(false);
            LabelIMGs.setText("SIN IMAGENES");
        } else {
            imgs = new ArrayList();
            while (ITimg.hasNext()) {
                imgs.add(cargarYescalar((String) ITimg.next(), LabelIMGs.getWidth(), LabelIMGs.getHeight()));
            }
            LabelIMGs.setText("");
            LabelIMGs.setIcon((ImageIcon) imgs.get(imagenSeleccionada));
        }

        lblNombre.setText(restaurante.getNombre());
        lblDireccion.setText(restaurante.getDireccion());
        lblMail.setText(restaurante.getEmail());
        lblNick.setText(restaurante.getNickname());

        Iterator it = quickorder2.QuickOrder2.port.restauranteGetCategorias(nick).iterator();

        String cat = "";
        while (it.hasNext()) {
            cat += it.next().toString();
            if (it.hasNext()) {
                cat += ", ";
            } else {
                cat += ".";
            }
        }

        lblCategorias.setText("<html>" + cat + "</html>");

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();

        modelo.setColumnIdentifiers(new Object[]{"Nombre", "Descripcion", "Tipo", "Precio"});

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        Iterator individuales = quickorder2.QuickOrder2.port.restauranteGetIndividuales(nick).iterator();

        while (individuales.hasNext()) {
            webservices.DataIndividual producto = (webservices.DataIndividual) individuales.next();
            modelo.addRow(new Object[]{producto.getNombre(), producto.getDescripcion(), "Individual", producto.getPrecio()});
        }

        Iterator promociones = quickorder2.QuickOrder2.port.restauranteGetPromociones(nick).iterator();

        while (promociones.hasNext()) {
            webservices.DataPromocion producto = (webservices.DataPromocion) promociones.next();
            modelo.addRow(new Object[]{producto.getNombre(), producto.getDescripcion(), "Promocion", producto.getPrecio()});
        }

        tablaProductos.setModel(modelo);

        this.setTitle("Datos del restaurante " + restaurante.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        LabelIMGs = new javax.swing.JLabel();
        BtnAdelante = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos del restaurante X");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Nickname:");

        jLabel4.setText("Email:");

        jLabel5.setText("Direccion:");

        lblNombre.setText("Nombre");

        lblDireccion.setText("Direccion");

        lblMail.setText("Email");

        lblNick.setText("Nick");

        jLabel7.setText("Categorias:");

        lblCategorias.setText("Caegoria1, Categoria 2, Categoria 3.");
        lblCategorias.setMaximumSize(new java.awt.Dimension(179, 42));

        jLabel8.setText("Productos:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        LabelIMGs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIMGs.setText("IMG");
        LabelIMGs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnAdelante.setText(">");
        BtnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdelanteActionPerformed(evt);
            }
        });

        BtnAtras.setText("<");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64)
                                .addComponent(lblNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(61, 61, 61)
                                .addComponent(lblDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(80, 80, 80)
                                .addComponent(lblMail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)
                                .addComponent(lblNick))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52)
                                .addComponent(lblCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelIMGs, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAdelante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIMGs, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdelante)
                    .addComponent(BtnAtras))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblMail))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblNick))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        if (imagenSeleccionada == 0) {
            imagenSeleccionada = imgs.size() - 1;
        } else {
            imagenSeleccionada--;
        }
         LabelIMGs.setIcon((ImageIcon) imgs.get(imagenSeleccionada));
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdelanteActionPerformed
        if (imagenSeleccionada > imgs.size() - 2) {
            imagenSeleccionada = 0;
        } else {
            imagenSeleccionada++;
        }
        LabelIMGs.setIcon((ImageIcon) imgs.get(imagenSeleccionada));
    }//GEN-LAST:event_BtnAdelanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetalleRestaurante dialog = new DetalleRestaurante(new javax.swing.JFrame(), "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdelante;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JLabel LabelIMGs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
