/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickorder2.Registro;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import quickorder2.Registro.Herramientas.SelectorMultiple;
import quickorder2.Registro.Herramientas.SelectorSimple;
import webservices.DataCliente;
import webservices.DataProdPedido;
import webservices.DataPromocion;
import webservices.DataRestaurante;
import webservices.Estado;

/**
 *
 * @author Jean
 */
public class Pedido extends javax.swing.JInternalFrame {

    public DataRestaurante restaurante;
    public DataCliente cliente;
    DefaultTableModel modeloTabla;
    public DataProdPedido[] productos = new DataProdPedido[]{};

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(modeloTabla);
        limpiarTabla();
        BtnAdd.setEnabled(false);
    }

    private void calcularTotal() {
        Float tot = (float) 0;
        for (DataProdPedido p : productos) {
            tot += (p.getCantidad() * p.getProducto().getPrecio());
        }
        LabelTotal.setText(tot.toString());
    }

    /*private void modificarCantidad(String nombre, int cantidad) {
     if (lineas.get(nombre) != null) {
     ((DataProdPedido) lineas.get(nombre)).setCantidad(cantidad);
     actualizarTotal();
     }
     }*/
    public void cargarTabla() {
        limpiarTabla();
        for (DataProdPedido dp : productos) {
            String tipo = "Individual";
            if (dp.getProducto() instanceof DataPromocion) {
                tipo = "Promocion";
            }

            modeloTabla.addRow(new Object[]{dp.getProducto().getNombre(), tipo, dp.getCantidad(), dp.getProducto().getPrecio(), (dp.getProducto().getPrecio() * dp.getCantidad())});
        }
        calcularTotal();
    }

    

    private void limpiarTabla() {
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuTabla = new javax.swing.JPopupMenu();
        add = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRestaurante = new javax.swing.JTextField();
        btnBuscarR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();

        add.setText("Agregar Producto");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        MenuTabla.add(add);

        delete.setText("Quitar Producto");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        MenuTabla.add(delete);

        edit.setText("Modificar Candidad");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        MenuTabla.add(edit);

        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);

        jLabel1.setText("Cliente: ");

        txtCliente.setEditable(false);

        btnBuscarC.setText("Buscar");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        jLabel2.setText("Restaurante:");

        txtRestaurante.setEditable(false);

        btnBuscarR.setText("Buscar");
        btnBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Tipo", "Cant", "Precio U", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(MenuTabla);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTable1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTable1VetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(2);
        }

        jLabel3.setText("Productos:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        BtnAdd.setText("Agregar");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        jLabel4.setText("Total: $");

        LabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarC))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarR))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(Cancelar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(BtnAdd, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarR))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelTotal))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        SelectorSimple s = new SelectorSimple(null);
        s.cargarClientes();
        s.setVisible(true);
        if (s.resultado != null) {
            this.cliente = (DataCliente) s.resultado;
            txtCliente.setText(cliente.getNombre() + " " + cliente.getApellido());
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    private void btnBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRActionPerformed
        SelectorSimple s = new SelectorSimple(null);
        s.cargarRestaurantes();
        s.setVisible(true);
        if (s.resultado != null) {
            this.restaurante = (webservices.DataRestaurante) s.resultado;
            txtRestaurante.setText(restaurante.getNombre());
            limpiarTabla();
            BtnAdd.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarRActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased

    }//GEN-LAST:event_jTable1MouseReleased

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        SelectorMultiple s = new SelectorMultiple(null);
        s.cargarProductos(productos, restaurante.getNickname());
        s.setVisible(true);
        
        productos = (DataProdPedido[]) s.resultado;
        cargarTabla();
    }//GEN-LAST:event_BtnAddActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
/*
        SelectorProductosPedido s = new SelectorProductosPedido(null, this);
        s.cargarProductos();
        s.setVisible(true);
*/
    }//GEN-LAST:event_addActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
/*
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow > -1) {
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            String nom = String.valueOf(tm.getValueAt(jTable1.getSelectedRow(), 0));
            lineas.remove(nom);
            modeloTabla.removeRow(selectedRow);
            actualizarTotal();
        }
*/
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged

    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jTable1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTable1VetoableChange

    }//GEN-LAST:event_jTable1VetoableChange

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

/*        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow > -1) {
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            String nom = String.valueOf(tm.getValueAt(jTable1.getSelectedRow(), 0));
            int cant = Integer.parseInt(JOptionPane.showInputDialog(null,
                    "Modifcar Cantidad"));
            tm.setValueAt(cant, jTable1.getSelectedRow(), 2);
            tm.setValueAt(cant * ((DataProdPedido) (productos.get(nom))).getProducto().getPrecio(), jTable1.getSelectedRow(), 4);
            modificarCantidad(nom, cant);
            calcularTotal();
        }
*/        
    }//GEN-LAST:event_editActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        List<DataProdPedido> prods = new ArrayList<>();
        
        for(DataProdPedido p : productos){
            prods.add(p);
        }

        Calendar fecha = new java.util.GregorianCalendar();
        String anio = String.valueOf(fecha.get(Calendar.YEAR));
        String mes = String.valueOf(fecha.get(Calendar.MONTH));
        String dia = String.valueOf(fecha.get(Calendar.DAY_OF_MONTH));

        quickorder2.QuickOrder2.port.insertarPedido(dia, mes, anio, Estado.PREPARACION,
                cliente.getNickname(), restaurante.getNickname(), (List) prods);

        this.dispose();

    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JPopupMenu MenuTabla;
    private javax.swing.JMenuItem add;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnBuscarR;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenuItem edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtRestaurante;
    // End of variables declaration//GEN-END:variables
}
