/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickorder2.Registro;

import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quickorder2.Registro.Herramientas.SelectorMultiple;
import quickorder2.Registro.Herramientas.SelectorSimple;

/**
 *
 * @author Mauro
 */
public class Promocion extends javax.swing.JInternalFrame {

    public webservices.DataRestaurante restaurante;
    public webservices.DataProdPromo[] productos = new webservices.DataProdPromo[]{};

    /**
     * Creates new form Promocion
     */
    public Promocion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarR1 = new javax.swing.JButton();
        txtRestaurante1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscarR = new javax.swing.JButton();
        txtRestaurante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();

        btnBuscarR1.setText("Buscar");
        btnBuscarR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarR1ActionPerformed(evt);
            }
        });

        txtRestaurante1.setEditable(false);
        txtRestaurante1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Restaurante:");

        jLabel3.setText("Nombre:");

        setClosable(true);

        btnBuscarR.setText("Buscar");
        btnBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRActionPerformed(evt);
            }
        });

        txtRestaurante.setEditable(false);
        txtRestaurante.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Restaurante:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Productos:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jLabel4.setText("Subtotal:");

        txtSubtotal.setEditable(false);
        txtSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubtotal.setText("$ ");

        jLabel7.setText("Descuento:");

        txtDescuento.setText("% ");
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        jLabel8.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setText("$ ");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnRegistrar1.setText("Registrar");

        btnCancelar1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRestaurante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarR))
                            .addComponent(txtNombre1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubtotal)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(txtTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnQuitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1)
                    .addComponent(btnRegistrar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRActionPerformed
        SelectorSimple s = new SelectorSimple(null, this);
        s.cargarRestaurantes();
        s.setVisible(true);
        this.restaurante = (webservices.DataRestaurante) s.resultado;
        txtRestaurante.setText(restaurante.getNombre());
    }//GEN-LAST:event_btnBuscarRActionPerformed

    private void btnBuscarR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarR1ActionPerformed
        SelectorSimple s = new SelectorSimple(null, this);
        s.cargarRestaurantes();
        s.setVisible(true);
        this.restaurante = (webservices.DataRestaurante) s.resultado;
        txtRestaurante.setText(restaurante.getNombre());
    }//GEN-LAST:event_btnBuscarR1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtRestaurante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un restaurante.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (quickorder2.QuickOrder2.port.buscarRestaurante(restaurante.getNickname()) == null) {
            JOptionPane.showMessageDialog(this, "El restaurante ingresado no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            SelectorMultiple s = new SelectorMultiple(null);
            s.cargarIndividuales(productos, restaurante.getNickname());

            s.setVisible(true);
            productos = (webservices.DataProdPromo[]) s.resultado;
            
            cargarTabla(productos);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        HashMap aux = new HashMap();
        
        for(int i = 0 ; i < productos.length ; i++){
            aux.put(productos[i].getIndividual().getNombre(), productos[i]);
        }
        
        for(int i = 0 ; i < tablaProductos.getSelectedRows().length ; i++){
            aux.remove(tablaProductos.getValueAt(tablaProductos.getSelectedRows()[i], 0));
        }
        
        webservices.DataProdPromo[] resultado = new webservices.DataProdPromo[aux.values().size()];
        
        for(int i = 0 ; i < resultado.length ; i++){
            resultado[i] = (webservices.DataProdPromo) aux.values().toArray()[i];
        }
        productos = resultado;
        
        cargarTabla(productos);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
                if (evt.getKeyChar() == '.') {
            if (txtDescuento.getText().contains(",")) {
                evt.setKeyChar('\u0000');
            } else {
                evt.setKeyChar(',');
            }
        }

        if (!((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() == ',')) {
            evt.setKeyChar('\u0000');
        }

        if (txtDescuento.getText().equals("%") || txtDescuento.getText().isEmpty()) {
            txtDescuento.setText("% ");
        }
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
        calcularTotales();
    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void cargarTabla(webservices.DataProdPromo[] productos) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Nombre", "Descripcion", "Precio individual", "Cantidad", "Subtotal"});
        for (webservices.DataProdPromo producto : productos) {
            modelo.addRow(new Object[]{producto.getIndividual().getNombre(), producto.getIndividual().getDescripcion(), "$ " + producto.getIndividual().getPrecio(), producto.getCantidad(), producto.getCantidad() * producto.getIndividual().getPrecio()});
        }
        tablaProductos.setModel(modelo);
        calcularTotales();
    }
    
    private void calcularTotales(){
        double subtotal = 0;
        for(int i = 0 ; i < tablaProductos.getRowCount() ; i++){
            subtotal += Double.valueOf(tablaProductos.getValueAt(i, tablaProductos.getColumnCount()-1).toString());
        }
        txtSubtotal.setText("$ " + subtotal);
        
        Double descuento;
                
        if(txtDescuento.getText().substring(2).isEmpty()){
            descuento = 0.0;
        }else{
            descuento = (Double.valueOf(txtDescuento.getText().substring(2)) /100) * Double.valueOf(txtSubtotal.getText().substring(2));
        }
        
        txtTotal.setText("$ " + String.valueOf(Double.valueOf(txtSubtotal.getText().substring(2)) - descuento));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarR;
    private javax.swing.JButton btnBuscarR1;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtRestaurante;
    private javax.swing.JTextField txtRestaurante1;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
